package io.coodle.easyshop.orderservice.statemachine;

public enum OrderState {
    CREATED,
    PENDING_VALIDATION, VALIDATED, VALIDATION_ERROR,
    PENDING_ALLOCATION, ALLOCATED, ALLOCATION_ERROR, PENDING_INVENTORY,
    PAID,
    COMPLETED,
    PICKED_UP,
    DELIVERED, DELIVERY_ERROR,
    CANCELED,
    RETURNED,
    REFUND_APPLIED
}
